### ISSUE TITLE
S1/S2 switch type incorrect after automatic discovery

### ISSUE THREAD

**Issue by tyron** [diablodale/nanodimmer#1]
After setting S1/S2 to automatic discover and clicking the button, the parameter stored on the circuit changes from 4 to the proper value (1 for 2-state switches). It would be good if pressing the refresh button on the UI forced all parameters to be re-read from the device.

I thought that was the goal with the "refresh double press", but looks like this is not working. Nothing gets changed.

**Comment by diablodale** [comment]
Hi. I don't have enough information to diagnose what you describe. To help further, I will need more detailed information including

* setup: what is your hardware, wiring, etc.
* steps to reproduce: detail every step, every button, every swipe, every text/data/value you see. For example you write "parameter storedon the circuit changes...". How do you know that? Where did you see that? And write "click the button". What button and where?
* the result you expect as compared to the result you actually got. For example, I don't know what "nothing gets changed" means nor do I know where you are looking for changed things.

A look at the double-press code here loops through every configuration value the dimmer exposes and requests the current value from the dimmer using zwave commands.
https://github.com/diablodale/nanodimmer/blob/45f0a746b8ce814ed9211ce5e94ff195657b475d/nano-dimmer.groovy#L225
Asynchronously, the dimmer sends the requested config values to the smartthings hub and is received in this groovy code. The code caches the values in the smartthings hub so that in the future it can render text/numbers in a tile on your phone -or- can identify that when you change a setting in the config UI that the changed setting is sent via zwave to the dimmer itself.

**Comment by tyron** [comment]
Thanks for your reply @diablodale . I was looking more into the issue and now I'm understanding how it works. Sorry, I'm very new to Z-Wave.

Setup:
- Nano Dimmer installed according to instructions (live, neutral, load, switch for external switch)
- COM connected to an external switch, as well as S1 (2-state switch)

Steps to reproduce:
1. using nanodimmer, update "S1 Switch Type" (param 120) to "Automatic" (value 4)
1. toggle the external switch immediately and wait at least 10 seconds
1. internally, Aeotec Nano Dimmer will set param 120 to value 1 (because I have a 2-state switch). This can be confirmed using [zwave-tweaker](https://github.com/codersaur/SmartThings/blob/master/devices/zwave-tweaker/zwave-tweaker.groovy)
1. clicking refresh tile once or twice will fetch the values from the dimmer, but they are not updated on the system (aka device detail's page or settings on the Smartthings Classic app)

Looking into the code, I'm now understanding the new value gets requested through the loop you mentioned, but this is not updating the settings on the controller -- this seems to be failing:
https://github.com/diablodale/nanodimmer/blob/45f0a746b8ce814ed9211ce5e94ff195657b475d/nano-dimmer.groovy#L375

I'm wondering if this might be related to security constraints mentioned here on lines 998-1006: [zwave-tweaker.groovy](https://github.com/codersaur/SmartThings/blob/ec9ae325344f02b5073b7705542025cfa7406b01/devices/zwave-tweaker/zwave-tweaker.groovy#L998-L1006)

**Comment by diablodale** [comment]
Hi. We're making progress. :-) I still need more information on step 4.
What is the result you expect? Specifically...what text or image are you expecting in what location?
What is the result you actually get?

**Comment by tyron** [comment]
Since there is a disconnect from the values cached on Smartthings hub and the device itself, I would expect a way to reconcile this information. 
We already have a way to override from hub -> device, by clicking the "Configure" button on Smartthings Classic app (that should be showing the orange dot), which will force the cached information to the device. What I am looking here is the opposite process: a way to reconcile device -> hub, re-caching the hub based on the current state of the device.

Back to your question, the result I expect is to have the value current on the device shown everywhere on the hub console. I want to log into the web UI, go to "My Devices", select my dimmer, look at the Preferences line regarding param 120 and see the value "1". When I go to this screen, I'm still seeing the value "4", which is the last known by the device handler -- but that has been updated to "1" on the device.

Similarly, if I go to the settings on the Smartthings Classic App and I look into the "S1 Switch Type", I still see "Automatic" selected.
> Steps to reproduce:
> 
> 1. using nanodimmer, update "S1 Switch Type" (param 120) to "Automatic" (value 4)

I expected this to display "2-state switch" (value 1).

**Comment by diablodale** [comment]
Got it. In short, little of what you seek is possible with the Smartthings infrastructure.

In the app, goto 'my home', things, then click on the nanodimmer, this presents a UI that can be customized and much of it controlled with groovy code. Colors, text, tiles...almost all of it can be programmatically controlled.

https://github.com/diablodale/nanodimmer/blob/45f0a746b8ce814ed9211ce5e94ff195657b475d/nano-dimmer.groovy#L58

On that device UI, if you click the gear icon at the top right, that takes you to the preferences (aka settings) UI. This UI is very restricted. Groovy code can only define the list of preferences, the value type of each preference (e.g. boolean, byte, list), the possible values (e.g. true, 42, [0,1,2,3]), and a initial default value.

There is no possibility (due to the architectural limitation of Smartthings) to dynamically update the preferences UI. It is a one-way source of data. The preferences UI can send data to groovy. The preferences UI _can not_ receive data from groovy.

When you choose the automatic=4 value for preference=120 "switch type", that pair "pref120=4" is received by the groovy code and it forwarded to the nanodimmer with zwave. Sometime in the future asynchronously, the dimmer may or may not respond to that. Perhaps the dimmer does it on its own. Or perhaps it does it when you double-press the refresh tile in the app UI.

In either case, when the groovy code receives the asynchronous zwave event...
https://github.com/diablodale/nanodimmer/blob/45f0a746b8ce814ed9211ce5e94ff195657b475d/nano-dimmer.groovy#L365
it saves the received pair (pref120=1 in your scenario) into a variable that only groovy can see. It can't save this pref120=1 into the preferences/gear UI. Smartthings doesn't have that ability.

This extends also to the technical UI at graph.api.smartthings.com. This UI is also limited by Smartthings architectural limitations. Therefore, when you click down into a device and look at the "Preferences" row, you will see the values selected in the app's preferences/gear page. You will not see dynamically updated values retrieved from the dimmer because that data flow direction is architecturally not possible.

✔  preferencesUI -> groovy
❌  preferencesUI <- groovy

The only things that can be dynamically changed by groovy code is the device UI with all the tiles. For example, the groovy code in the project writes the "5 W" for power, writes the "5400 kWh", changes the configure tile's PNG to have an orange dot or not, writes "3-wire Resistive Trailing-edge" in one of the tiles, etc.

So it *is* possible to change the groovy code so that a tile shows the value of preference 120. For example, could remove one of the lines in the "3-wire..." tile and replace it with the text for "2-state, 3-way, momentary, ...". Or since it is a https://docs.smartthings.com/en/latest/device-type-developers-guide/tiles-metadata.html#multi-attribute-tiles, could use the SECONDARY_CONTROL tile attribute to show that switch text.

**Comment by tyron** [comment]
Thanks for the long and detailed explanation! I'll definitely keep this on my bookmarks as a reference on ST/groovy!
I'm closing this issue because it doesn't apply then. We could still update to have a tile displaying the correct value as you pointed out, but once you send new changes to the devices, that would be overwritten. Having it temporarily correct on the UI could cause even more confusion.

**Comment by diablodale** [comment]
As a hacking opportunity, there might be three issues. My dimmer is in the ceiling without a connection to S1/S2, so I can't test. But tracing the code, there might be an issue. And while fixing it, perhaps an opportunity to get part of your goal.

Looking back at the dimmer's params, there is only S1, S2 switch type (aka params 120,121) that have an "automatic detection" mechanism that is user-selectable. Other auto-detects are not selectable (e.g. 130=load type).

Assume that you have a 2-way switch connected to S1...

The Groovy code maintains its own cached copy of parameters and values in a variable `state.cachedDeviceParameters`. It is likely that when this Groovy device handler/dimmer was initially installed, all the params on the dimmer were automatically queried and therefore the `cachedDeviceParameters` already has values. So in a fresh out-of-the-box dimmer scenario, might equal `cachedDeviceParameters.p120=undefined`

When you set S1=auto (param 120) in the settings UI, that's saved by SmartThings itself into the Groovy `settings`  read-only variable. For brevity, I'll write that as `settings.p120=auto`

### Bug 1?

Then SmartThings calls `updated()` which calls `configure()` which calls `update_settings_on_device()`. In that code, an `if` clause will find that `cachedDeviceParameters.p120 != settings.p120` aka `undefined != auto`. This causes a `set` zwave command to be sent to the dimmer to set p120=auto and a `get` zwave command to get the value after the set. The set followed immediately by a get may not provide enough time for you to physically click S1 and the dimmer to do its detection. Also, I don't see in the dimmer's documentation that it will spontaneously send the detected p120 after it determines it. This may be a race condition.

### Bug 2?

Lets assume that Bug 1 doesn't exist and continue. Somehow (dimmer itself, user clicked refresh tile, etc.) the dimmer sent the detected value of p120 to SmartThings via zwave. When this value is received, `update_cached_device_parameters()` is called. In that function it saves this new value `cachedDeviceParameters.p120=2way`. That code then detects that `cachedDeviceParameters.p120 != settings.p120` aka `2way != auto`. This causes the configure tile to have an orange dot on it.

I think this orange dot is undesired. Since S1=auto was selected and the dimmer did its job to detect it, it doesn't make sense to put an orange dot on the config tile in this situation. It is possible in Groovy code to ignore this case of params 120,121 when `settings.p120 == auto` and `cachedDeviceParameters.p120 != auto`. It is also possible in this function to update the list of params that have tiles (new one for switches?) and the matching tile code in `update_tiles()`.

### Bug 3?

Lets keep going. In the current code, now there is an orange dot. So sometimes now or in the future, a user clicks to configure. Configure is really "force upload dimmer params". The tiles/UI of this device handlers is mostly the same as the previous author + bug fixes. I left the configure tile the same. When that dot appears, it means that the locally `cachedDeviceParameters` doesn't match the `settings` page.

Now when configure tile is clicked, the Groovy code will call `update_settings_on_device()` and that function will send the zwave command to the dimmer to set `p120=auto` because `settings.p120=auto` still. Now the dimmer is back in auto-detect mode, and we have a loop going back to **Bug 1** above
